#!/usr/bin/env sh

bspc monitor DP-0   -d 1 2 3 4 5 6  
bspc monitor HDMI-1 -d 7 8 9 

# TODO

bspc config focus_follows_pointer true
bspc config border_width          2
bspc config window_gap            16
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Spotify desktop=8
bspc rule -a firefox desktop=2
