#!/usr/bin/env sh
ffmpeg -f rawvideo -pix_fmt rgb555 -s 42x42 -r 25 \
       -i $1 -f u8 -ar 44100 -ac 2 \
       -i $1 -sws_flags neighbor -s 240x240 \
       -vf scale=w=32*iw:h=32*ih:sws_flags=neighbor -b:v 50000k something.mp4 -y

mpv something.mp4
