#!/usr/bin/env bash
time="$(date '+%a, %H:%M:%S')"
printf '%s\n' "${time,,}"

function calendar() {
  # yes i use retarded bashisms to save myself some time
  cal=$(cal)
  today=$(date +%d)
  body=$(tail -n+2 <<< $cal)
  dunstify "$(head -n1 <<< $cal)" "${body/$today/<b>$today</b>}"
}

case $BLOCK_BUTTON in
    1) calendar ;;
esac
