#!/usr/bin/env sh
## MUSic Title
data="$(playerctl -p spotify metadata)"
artist="$(echo "$data" | grep artist | cut -c 35-)"
title="$(echo "$data" | grep title | cut -c 35-)"
printf '%s\n' "$artist - $title"


case $BLOCK_BUTTON in 
  1) playerctl -p spotify next && pkill -RTMIN+4 dwmblocks;;
  2) playerctl -p spotify play-pause && pkill -RTMIN+4 dwmblocks;;
  3) playerctl -p spotify previous && pkill -RTMIN+4 dwmblocks;;
esac
