#!/usr/bin/env sh
# fusion of monesonn/doasedit and koalagang/doasedit
set -ex

err () { echo "$1" && exit 1 ; }

# checking
[ ! $(id -u) -eq 0 ] || err 'cannot be run as root'
[ $# = 0 ] && err 'no arguments'
[ $# = 1 ] || err 'too many arguments'
[ $EDITOR ] || err 'no editor set'

# creating
temp=$(mktemp --suffix=dead)
[ -f $1 ] && cat $1 > $temp
${EDITOR} $temp
cmp "$1" $temp -s && echo "$1 unchanged" && rm -v $temp && exit 0

# writing
atmpt=0
until doas cp -f $temp $1; do
    atmpt=$((attempt + 1))
    [ $atmpt -ge 3 ] && err "cannot accept changes, manually cp $temp"
    doas chown root:root $1 && doas chmod 0444 $1
done
rm -v $temp
