#!/usr/bin/env sh
## shitty linux fetch
# stolen from fet.sh, catfetch
sep=" ~ "
color="35"

# host name, kernel version, wm, distro, term
read -r hostname < /proc/sys/kernel/hostname
read -r kernel < /proc/sys/kernel/osrelease
wm=${WAYLAND_DISPLAY:-$(xprop -id "$(xprop -root _NET_SUPPORTING_WM_CHECK | cut -d' ' -f5)" _NET_WM_NAME | cut -d'"' -f2)}
. /etc/os-release
[ $TERM = linux ] && term=$(tty) || term=${TERM%%-*}

# uptime
IFS=. read -r i _ < /proc/uptime
hour="$((i / 60 / 60 % 24))"
min="$((i / 60 % 60))"
uptime="$((i % 60))s"
[ $min -gt 0 ] && uptime="${min}m $uptime"
[ $hour -gt 0 ] && uptime="${hour}h $uptime"

for i in '/var/db/kiss/installed/*'  '/var/lib/pacman/local/[0-9a-z]*' '/var/db/xbps/.*'  '/var/db/pkg/*/*'; do
	set -- $i
	[ $# -gt 1 ] && pkgs=$# && break
done

print() {
    printf "\033[1;%sm%10s\033[39m%s\033[0m\033[39m%s\n\033[0m" \
                  "$1" "$2"   "${4:-$sep}"                "$3"
}

get_hardware() {
  read -r board < /sys/class/dmi/id/board_name
  read -r sys < /sys/class/dmi/id/sys_vendor
  while read -r line; do
  	case $line in
  		vendor_id*) vendor="${line##*: } ";;
  		model\ name*) cpu=${line##*: }; break;;
  	esac
  done < /proc/cpuinfo
  cpu=${cpu% CPU*}
  cpu=${cpu#*Core(TM) *}

  while read -r line; do
    case $line in
  		*VGA*) gpu=${line##*: } ;;
    esac 
  done <<-EOF
 $(lspci -G)
EOF
  gpu=${gpu#*[}
  gpu=${gpu%]*}
  gpu=$(echo $gpu | tr 'GeForce' 'NoVideo')
  gpu=${gpu%Rov*}

  while IFS=': ' read -r n v _; do
    case $n in
  		MemTotal) mem=$(($v / 1024)) ;;
    esac
  done < /proc/meminfo
}
get_hardware

echo
print 95 "whoami" "$hostname" " - "
print 95 "whoareu" "$USER" " - "
print $color distro "$PRETTY_NAME"
print $color kernel "$kernel"
print $color shell "${SHELL##*/}"
print $color pkgs "$pkgs"
print $color uptime "$uptime"
print $color memory "$mem"
print $color gfx "$gpu"
print $color cpu "$cpu"
print $color wm "$wm"
print $color term "$term"
echo
