#!/usr/bin/env bash

selected="$(ps -a -u $USER -o '%p  %c' | \
            dmenu -p "kill" | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
fi

exit 0
