#!/usr/bin/env bash
# stackoverflow.com/questions/35927760

cmd="mpv /data/vids/funny/blursed_disney-kth79mhr65e81.mp4"

readarray -t lines < <($cmd)
for line in "${lines[@]}"; do
  notify-send "$line"
done

# while read -r l1 ;do
#   dunstify -r 2284 "$l1"
# done 
  # set -x
# play_mpv ;;
# OPTS="mpv play from clipboard
# "
# 
# case $(printf "$OPTS" | dmenu -p "media") in
#   mpv*) play_mpv ;;
# esac
